// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RaidBot.Data;

#nullable disable

namespace RaidBot.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230417044438_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DSharpPlus.Entities.DiscordRole", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("DiscordMemberId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("IconHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsHoisted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsManaged")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMentionable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Permissions")
                        .HasColumnType("bigint");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiscordMemberId");

                    b.ToTable("DiscordRole");
                });

            modelBuilder.Entity("DSharpPlus.Entities.DiscordUser", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("AvatarHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BannerHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Flags")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBot")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("MfaEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("OAuthFlags")
                        .HasColumnType("integer");

                    b.Property<int?>("PremiumType")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Verified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("DiscordUser");

                    b.HasDiscriminator<string>("Discriminator").HasValue("DiscordUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RaidBot.entities.AssignedTierRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .HasColumnType("text");

                    b.Property<int>("TierRoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TierRoleId");

                    b.ToTable("AssignedTierRoles");
                });

            modelBuilder.Entity("RaidBot.entities.BackUpRoster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BackUpSettingsId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MemberId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int?>("RaidSettingsId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("BackUpSettingsId");

                    b.HasIndex("MemberId");

                    b.HasIndex("RaidSettingsId");

                    b.HasIndex("RoleId");

                    b.ToTable("BackUp");
                });

            modelBuilder.Entity("RaidBot.entities.GuildMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DiscordMemberId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DiscordMemberId");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildMember");
                });

            modelBuilder.Entity("RaidBot.entities.GuildSettings", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("RaidChannelGroup")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("RaidChannelId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId");

                    b.ToTable("GuildSettings");
                });

            modelBuilder.Entity("RaidBot.entities.OverFlowRoster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("MemberId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("OverflowSettingsId")
                        .HasColumnType("integer");

                    b.Property<int?>("RaidSettingsId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("OverflowSettingsId");

                    b.HasIndex("RaidSettingsId");

                    b.HasIndex("RoleId");

                    b.ToTable("OverFlowRoster");
                });

            modelBuilder.Entity("RaidBot.entities.RaidRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DpsRole")
                        .HasColumnType("integer");

                    b.Property<int?>("HealerRole")
                        .HasColumnType("integer");

                    b.Property<int>("RoleSettingsId")
                        .HasColumnType("integer");

                    b.Property<int?>("TankRole")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleSettingsId")
                        .IsUnique();

                    b.ToTable("RaidRoles");
                });

            modelBuilder.Entity("RaidBot.entities.RaidSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Info")
                        .HasColumnType("text");

                    b.Property<string>("RaidName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RolesId")
                        .HasColumnType("integer");

                    b.Property<string>("TierRole")
                        .HasColumnType("text");

                    b.Property<TimeSpan?>("Time")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.HasIndex("RolesId");

                    b.ToTable("RaidSettings");
                });

            modelBuilder.Entity("RaidBot.entities.RaidStatsByRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("RaidHistoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<int?>("UserRaidHistoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RaidHistoryId");

                    b.HasIndex("UserRaidHistoryId");

                    b.ToTable("RaidStatsByRoles");
                });

            modelBuilder.Entity("RaidBot.entities.RaidStatsByTier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RaidHistoryId")
                        .HasColumnType("integer");

                    b.Property<int>("TierCount")
                        .HasColumnType("integer");

                    b.Property<string>("TierName")
                        .HasColumnType("text");

                    b.Property<int?>("UserRaidHistoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RaidHistoryId");

                    b.HasIndex("UserRaidHistoryId");

                    b.ToTable("RaidStatsByTiers");
                });

            modelBuilder.Entity("RaidBot.entities.Roster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GroupMemberId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal?>("MemberId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int?>("RaidSettingsId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("RoleId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("RosterSettingsId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupMemberId");

                    b.HasIndex("MemberId");

                    b.HasIndex("RaidSettingsId");

                    b.HasIndex("RoleId");

                    b.HasIndex("RosterSettingsId");

                    b.ToTable("Rosters");
                });

            modelBuilder.Entity("RaidBot.entities.SignUpEmoji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EmojiName")
                        .HasColumnType("text");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("RaidRole")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("SignUpEmojis");
                });

            modelBuilder.Entity("RaidBot.entities.TierRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("TierName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("TierRoles");
                });

            modelBuilder.Entity("RaidBot.entities.UserRaidHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GuildMemberId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastRaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalRaidCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalRaidCountLastMonth")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GuildMemberId");

                    b.ToTable("UserRaidHistories");
                });

            modelBuilder.Entity("DSharpPlus.Entities.DiscordMember", b =>
                {
                    b.HasBaseType("DSharpPlus.Entities.DiscordUser");

                    b.Property<DateTimeOffset?>("CommunicationDisabledUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeafened")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsPending")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PremiumSince")
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue("DiscordMember");
                });

            modelBuilder.Entity("DSharpPlus.Entities.DiscordRole", b =>
                {
                    b.HasOne("DSharpPlus.Entities.DiscordMember", null)
                        .WithMany("Roles")
                        .HasForeignKey("DiscordMemberId");
                });

            modelBuilder.Entity("RaidBot.entities.AssignedTierRoles", b =>
                {
                    b.HasOne("RaidBot.entities.TierRole", "TierRole")
                        .WithMany("Roles")
                        .HasForeignKey("TierRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TierRole");
                });

            modelBuilder.Entity("RaidBot.entities.BackUpRoster", b =>
                {
                    b.HasOne("RaidBot.entities.RaidSettings", "RaidSettings")
                        .WithMany()
                        .HasForeignKey("BackUpSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DSharpPlus.Entities.DiscordMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");

                    b.HasOne("RaidBot.entities.RaidSettings", null)
                        .WithMany("BackUp")
                        .HasForeignKey("RaidSettingsId");

                    b.HasOne("DSharpPlus.Entities.DiscordRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Member");

                    b.Navigation("RaidSettings");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RaidBot.entities.GuildMember", b =>
                {
                    b.HasOne("DSharpPlus.Entities.DiscordMember", "DiscordMember")
                        .WithMany()
                        .HasForeignKey("DiscordMemberId");

                    b.HasOne("RaidBot.entities.GuildSettings", "GuildSettings")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscordMember");

                    b.Navigation("GuildSettings");
                });

            modelBuilder.Entity("RaidBot.entities.OverFlowRoster", b =>
                {
                    b.HasOne("DSharpPlus.Entities.DiscordMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");

                    b.HasOne("RaidBot.entities.RaidSettings", "RaidSettings")
                        .WithMany()
                        .HasForeignKey("OverflowSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaidBot.entities.RaidSettings", null)
                        .WithMany("OverFlow")
                        .HasForeignKey("RaidSettingsId");

                    b.HasOne("DSharpPlus.Entities.DiscordRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Member");

                    b.Navigation("RaidSettings");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RaidBot.entities.RaidRoles", b =>
                {
                    b.HasOne("RaidBot.entities.RaidSettings", "RaidSettings")
                        .WithOne()
                        .HasForeignKey("RaidBot.entities.RaidRoles", "RoleSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RaidSettings");
                });

            modelBuilder.Entity("RaidBot.entities.RaidSettings", b =>
                {
                    b.HasOne("RaidBot.entities.GuildSettings", "GuildSettings")
                        .WithMany("RaidList")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaidBot.entities.RaidRoles", "Roles")
                        .WithMany()
                        .HasForeignKey("RolesId");

                    b.Navigation("GuildSettings");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("RaidBot.entities.RaidStatsByRole", b =>
                {
                    b.HasOne("RaidBot.entities.UserRaidHistory", "UserRaidHistory")
                        .WithMany()
                        .HasForeignKey("RaidHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaidBot.entities.UserRaidHistory", null)
                        .WithMany("RaidStatsByRole")
                        .HasForeignKey("UserRaidHistoryId");

                    b.Navigation("UserRaidHistory");
                });

            modelBuilder.Entity("RaidBot.entities.RaidStatsByTier", b =>
                {
                    b.HasOne("RaidBot.entities.UserRaidHistory", "UserRaidHistory")
                        .WithMany()
                        .HasForeignKey("RaidHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RaidBot.entities.UserRaidHistory", null)
                        .WithMany("RaidStatsByTier")
                        .HasForeignKey("UserRaidHistoryId");

                    b.Navigation("UserRaidHistory");
                });

            modelBuilder.Entity("RaidBot.entities.Roster", b =>
                {
                    b.HasOne("DSharpPlus.Entities.DiscordUser", "GroupMember")
                        .WithMany()
                        .HasForeignKey("GroupMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DSharpPlus.Entities.DiscordMember", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");

                    b.HasOne("RaidBot.entities.RaidSettings", null)
                        .WithMany("Roster")
                        .HasForeignKey("RaidSettingsId");

                    b.HasOne("DSharpPlus.Entities.DiscordRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.HasOne("RaidBot.entities.RaidSettings", "RaidSettings")
                        .WithMany()
                        .HasForeignKey("RosterSettingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupMember");

                    b.Navigation("Member");

                    b.Navigation("RaidSettings");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RaidBot.entities.SignUpEmoji", b =>
                {
                    b.HasOne("RaidBot.entities.GuildSettings", "GuildSettings")
                        .WithMany("Emoji")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildSettings");
                });

            modelBuilder.Entity("RaidBot.entities.TierRole", b =>
                {
                    b.HasOne("RaidBot.entities.GuildSettings", "GuildSettings")
                        .WithMany()
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildSettings");
                });

            modelBuilder.Entity("RaidBot.entities.UserRaidHistory", b =>
                {
                    b.HasOne("RaidBot.entities.GuildMember", "GuildMember")
                        .WithMany()
                        .HasForeignKey("GuildMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuildMember");
                });

            modelBuilder.Entity("RaidBot.entities.GuildSettings", b =>
                {
                    b.Navigation("Emoji");

                    b.Navigation("RaidList");
                });

            modelBuilder.Entity("RaidBot.entities.RaidSettings", b =>
                {
                    b.Navigation("BackUp");

                    b.Navigation("OverFlow");

                    b.Navigation("Roster");
                });

            modelBuilder.Entity("RaidBot.entities.TierRole", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("RaidBot.entities.UserRaidHistory", b =>
                {
                    b.Navigation("RaidStatsByRole");

                    b.Navigation("RaidStatsByTier");
                });

            modelBuilder.Entity("DSharpPlus.Entities.DiscordMember", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
